modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="smoothmenu"
version="${file.jarVersion}"
displayName="Smooth Menu"
logoFile="logo.png"
authors="BookerCatch"
description="Uncaps the main menu's framerate limit."

[modproperties.smoothmenu]
    catalogueItemIcon="minecraft:redstone" # custom icon for Catalogue's mod list
    configBackground="minecraft:textures/block/stone_bricks.png" # background for Configured's generated config screen

[[dependencies.smoothmenu]]
    modId="forge"
    mandatory=true
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.smoothmenu]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
